/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package db;

/**
 *
 * @author iband
 */
public class Booking {
    
  private int bookId;           // book_id in MySQL
    private String ordernum;      // ordernum in MySQL (auto-generated by MySQL trigger)
    private String cname;         // cname in MySQL
    private String caddress;      // caddress in MySQL
    private String ctele;         // ctele in MySQL
    private String destination;   // destination in MySQL
    private int km;               // km in MySQL
    private int vehicleId;        // vehicle_id in MySQL
    private int driverId;         // driver_id in MySQL

    // Default constructor
    public Booking() {}

    // Parameterized constructor
    public Booking(int bookId, String ordernum, String cname, String caddress, String ctele, String destination, int km, int vehicleId, int driverId) {
        this.bookId = bookId;
        this.ordernum = ordernum;   // ordernum generated by MySQL trigger
        this.cname = cname;
        this.caddress = caddress;
        this.ctele = ctele;
        this.destination = destination;
        this.km = km;
        this.vehicleId = vehicleId;
        this.driverId = driverId;
    }

    // Getters & Setters
    public int getBookId() { return bookId; }
    public void setBookId(int bookId) { this.bookId = bookId; }

    public String getOrdernum() { return ordernum; }  // Getter for ordernum
    public void setOrdernum(String ordernum) { this.ordernum = ordernum; }  // Setter for ordernum

    public String getCname() { return cname; }
    public void setCname(String cname) { this.cname = cname; }

    public String getCaddress() { return caddress; }
    public void setCaddress(String caddress) { this.caddress = caddress; }

    public String getCtele() { return ctele; }
    public void setCtele(String ctele) { this.ctele = ctele; }

    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }

    public int getKm() { return km; }
    public void setKm(int km) { this.km = km; }

    public int getVehicleId() { return vehicleId; }
    public void setVehicleId(int vehicleId) { this.vehicleId = vehicleId; }

    public int getDriverId() { return driverId; }
    public void setDriverId(int driverId) { this.driverId = driverId; }
}
